name: "Runner@127.0.0.1"

api_endpoint: http://127.0.0.1:8888/api

runner:
  max_tasks_per_gpu: 2
  max_gpu_load: 1.0
  min_gpu_mem: 0.0
  use_gpu_indices: *

log_path: ~/.coordml

gpu_mode:
  fake: true
  gpu_num: 4
  gpu_name: Titan Xp
  gpu_mem: 31300
